version: "3.10"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    image: app:django
    container_name: django_container
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10

  nginx:
    build: ./app/nginx
    ports:
      - 80:80
    image: nginx:latest
    links:
      - app

